version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store_intelligence_api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
